import type {
  User,
  Team,
  Department,
  Organization,
  Ticket,
  Message,
  TicketStats,
  KpiStats,
  LlmCostStats,
} from "@/shared/types";

// --- Organizations, Departments, Teams ---

const mockOrganization: Organization = {
  id: "org-1",
  name: "테크 주식회사",
  code: "TECH",
};

const mockDepartment: Department = {
  id: "dept-1",
  organizationId: "org-1",
  name: "IT 운영팀",
  code: "IT-OPS",
  organization: mockOrganization,
};

const mockTeams: Team[] = [
  {
    id: "team-1",
    departmentId: "dept-1",
    name: "L1 지원팀",
    code: "L1-SUPPORT",
    department: mockDepartment,
  },
  {
    id: "team-2",
    departmentId: "dept-1",
    name: "L2 엔지니어링팀",
    code: "L2-ENG",
    department: mockDepartment,
  },
  {
    id: "team-3",
    departmentId: "dept-1",
    name: "관리팀",
    code: "ADMIN",
    department: mockDepartment,
  },
];

// --- Users ---

export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "kim@company.com",
    name: "김민수",
    role: "employee",
    teamId: "team-1",
    team: mockTeams[0],
  },
  {
    id: "user-2",
    email: "park@company.com",
    name: "박지영",
    role: "agent_l1",
    teamId: "team-1",
    team: mockTeams[0],
  },
  {
    id: "user-3",
    email: "lee@company.com",
    name: "이승호",
    role: "agent_l2",
    teamId: "team-2",
    team: mockTeams[1],
  },
  {
    id: "user-4",
    email: "choi@company.com",
    name: "최유진",
    role: "admin",
    teamId: "team-3",
    team: mockTeams[2],
  },
  {
    id: "user-5",
    email: "jung@company.com",
    name: "정하늘",
    role: "agent_l2",
    teamId: "team-2",
    team: mockTeams[1],
  },
];

// --- Tickets ---

export const mockTickets: Ticket[] = [
  {
    id: "ticket-1",
    ticketNumber: "TK-2024-001",
    subject: "VPN 연결이 안됩니다",
    status: "open",
    priority: "high",
    category: ["네트워크", "VPN"],
    requesterId: "user-1",
    assignedTo: null,
    createdVia: "web",
    confidenceScore: 0.85,
    resolutionType: null,
    createdAt: "2024-01-15T09:00:00Z",
    updatedAt: "2024-01-15T09:00:00Z",
    resolvedAt: null,
    requester: mockUsers[0],
    assignee: undefined,
  },
  {
    id: "ticket-2",
    ticketNumber: "TK-2024-002",
    subject: "이메일 비밀번호 초기화 요청",
    status: "in_progress",
    priority: "medium",
    category: ["계정", "비밀번호"],
    requesterId: "user-1",
    assignedTo: "user-2",
    createdVia: "web",
    confidenceScore: 0.92,
    resolutionType: "ai_auto",
    createdAt: "2024-01-14T14:30:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
    resolvedAt: null,
    requester: mockUsers[0],
    assignee: mockUsers[1],
  },
  {
    id: "ticket-3",
    ticketNumber: "TK-2024-003",
    subject: "프린터 드라이버 설치 요청",
    status: "resolved",
    priority: "low",
    category: ["하드웨어", "프린터"],
    requesterId: "user-1",
    assignedTo: "user-3",
    createdVia: "email",
    confidenceScore: 0.55,
    resolutionType: "agent_l2",
    createdAt: "2024-01-13T11:00:00Z",
    updatedAt: "2024-01-14T16:00:00Z",
    resolvedAt: "2024-01-14T16:00:00Z",
    requester: mockUsers[0],
    assignee: mockUsers[2],
  },
  {
    id: "ticket-4",
    ticketNumber: "TK-2024-004",
    subject: "소프트웨어 라이선스 갱신",
    status: "closed",
    priority: "medium",
    category: ["소프트웨어", "라이선스"],
    requesterId: "user-1",
    assignedTo: "user-5",
    createdVia: "web",
    confidenceScore: 0.45,
    resolutionType: "agent_l1",
    createdAt: "2024-01-10T08:00:00Z",
    updatedAt: "2024-01-12T17:00:00Z",
    resolvedAt: "2024-01-12T15:00:00Z",
    requester: mockUsers[0],
    assignee: mockUsers[4],
  },
];

// --- Messages (keyed by ticket id) ---

export const mockMessages: Record<string, Message[]> = {
  "ticket-1": [
    {
      id: "msg-1",
      ticketId: "ticket-1",
      senderId: "user-1",
      senderType: "user",
      visibility: "public",
      content: "오늘 아침부터 VPN 연결이 계속 실패합니다. 오류 코드 800이 뜹니다.",
      contentType: "text",
      attachments: null,
      source: "web",
      createdAt: "2024-01-15T09:00:00Z",
      sender: mockUsers[0],
    },
    {
      id: "msg-2",
      ticketId: "ticket-1",
      senderId: null,
      senderType: "ai",
      visibility: "public",
      content:
        "VPN 오류 코드 800은 일반적으로 서버 연결 문제를 나타냅니다. 다음 단계를 시도해 보세요:\n1. VPN 클라이언트를 재시작합니다.\n2. 네트워크 연결을 확인합니다.\n3. 방화벽 설정을 확인합니다.",
      contentType: "text",
      attachments: null,
      source: "ai_generated",
      createdAt: "2024-01-15T09:01:00Z",
      sender: undefined,
    },
    {
      id: "msg-3",
      ticketId: "ticket-1",
      senderId: "user-2",
      senderType: "agent_l1",
      visibility: "private",
      content: "AI 응답이 적절해 보입니다. 사용자 응답을 기다려봅니다.",
      contentType: "text",
      attachments: null,
      source: "web",
      createdAt: "2024-01-15T09:05:00Z",
      sender: mockUsers[1],
    },
  ],
  "ticket-2": [
    {
      id: "msg-4",
      ticketId: "ticket-2",
      senderId: "user-1",
      senderType: "user",
      visibility: "public",
      content: "이메일 비밀번호를 잊어버렸습니다. 초기화 부탁드립니다.",
      contentType: "text",
      attachments: null,
      source: "web",
      createdAt: "2024-01-14T14:30:00Z",
      sender: mockUsers[0],
    },
    {
      id: "msg-5",
      ticketId: "ticket-2",
      senderId: null,
      senderType: "ai",
      visibility: "public",
      content:
        "비밀번호 초기화 링크를 등록된 휴대폰 번호로 발송했습니다. 5분 내에 도착하지 않으면 다시 요청해 주세요.",
      contentType: "text",
      attachments: null,
      source: "ai_generated",
      createdAt: "2024-01-14T14:31:00Z",
      sender: undefined,
    },
    {
      id: "msg-6",
      ticketId: "ticket-2",
      senderId: "user-2",
      senderType: "agent_l1",
      visibility: "public",
      content: "비밀번호 초기화가 완료되었습니다. 새 비밀번호로 로그인해 주세요.",
      contentType: "text",
      attachments: null,
      source: "web",
      createdAt: "2024-01-15T10:00:00Z",
      sender: mockUsers[1],
    },
  ],
  "ticket-3": [
    {
      id: "msg-7",
      ticketId: "ticket-3",
      senderId: "user-1",
      senderType: "user",
      visibility: "public",
      content: "3층 공용 프린터 드라이버를 설치해 주세요.",
      contentType: "text",
      attachments: null,
      source: "email",
      createdAt: "2024-01-13T11:00:00Z",
      sender: mockUsers[0],
    },
    {
      id: "msg-8",
      ticketId: "ticket-3",
      senderId: "user-3",
      senderType: "agent_l2",
      visibility: "public",
      content: "원격으로 프린터 드라이버를 설치 완료했습니다. 테스트 인쇄를 해보시고 문제가 있으면 알려주세요.",
      contentType: "text",
      attachments: null,
      source: "web",
      createdAt: "2024-01-14T16:00:00Z",
      sender: mockUsers[2],
    },
  ],
  "ticket-4": [
    {
      id: "msg-9",
      ticketId: "ticket-4",
      senderId: "user-1",
      senderType: "user",
      visibility: "public",
      content: "Adobe Creative Suite 라이선스가 만료되었습니다. 갱신 부탁드립니다.",
      contentType: "text",
      attachments: null,
      source: "web",
      createdAt: "2024-01-10T08:00:00Z",
      sender: mockUsers[0],
    },
    {
      id: "msg-10",
      ticketId: "ticket-4",
      senderId: null,
      senderType: "system",
      visibility: "private",
      content: "AI 신뢰도 점수가 낮아 L2 에이전트에게 자동 배정되었습니다.",
      contentType: "text",
      attachments: null,
      source: "ai_generated",
      createdAt: "2024-01-10T08:01:00Z",
      sender: undefined,
    },
    {
      id: "msg-11",
      ticketId: "ticket-4",
      senderId: "user-5",
      senderType: "agent_l2",
      visibility: "public",
      content: "라이선스 갱신이 완료되었습니다. 소프트웨어를 재시작하면 적용됩니다.",
      contentType: "text",
      attachments: null,
      source: "web",
      createdAt: "2024-01-12T15:00:00Z",
      sender: mockUsers[4],
    },
  ],
};

// --- Statistics ---

export const mockTicketStats: TicketStats = {
  total: 156,
  open: 23,
  inProgress: 18,
  resolved: 98,
  closed: 17,
};

export const mockKpiStats: KpiStats = {
  resolutionRate: 0.72,
  routingAccuracy: 0.91,
  avgProcessingTimeHours: 2.4,
};

export const mockLlmCostStats: LlmCostStats = {
  totalCost: 47.82,
  byModel: [
    { model: "claude-3-haiku", cost: 12.45, calls: 3420 },
    { model: "claude-3-sonnet", cost: 35.37, calls: 890 },
  ],
  byPeriod: [
    { date: "2024-01-09", cost: 6.12 },
    { date: "2024-01-10", cost: 7.34 },
    { date: "2024-01-11", cost: 5.89 },
    { date: "2024-01-12", cost: 8.21 },
    { date: "2024-01-13", cost: 6.45 },
    { date: "2024-01-14", cost: 7.02 },
    { date: "2024-01-15", cost: 6.79 },
  ],
};
